# Packages

```{r}
library(tidyverse)
library(mice)
```

# loading data

```{r setup, echo=TRUE, results='hide', warning=FALSE, message=FALSE}
# load prices
url = 'https://raw.githubusercontent.com/schoolkidrich/housing_price/main/train.csv'

prices = read.csv(url, stringsAsFactors = TRUE)
```


### Research question 

What factors are relevant in determining house price? 


```{r}
# each row represents one house 
num_cases = dim(prices)[1]
print(paste("There are",num_cases,"cases"))
```


# Notice that there are missing data

```{r}
summary(prices)
```

# cleaning data

```{r}
# drop columns with more than 33% as NA
col_names = names(prices)
na_count = map(prices, ~sum(is.na(.)))

drop = c()
for (name in col_names){
  if (na_count[name] > (num_cases/3)){
    drop = c(drop,name)
  }
}
```

# Need to drop Utilities column due to lack of diversity

```{r}
prices%>% 
  ggplot(aes(x=Utilities))+geom_bar()
```

# drop values and impute missing data

```{r}
# drop Id column
drop = c(drop, "Id", 'Utilities')
dropped = prices[,!(names(prices) %in% drop)]

imputed = dropped%>%
  # impute missing values
  type.convert(.)%>%
  mice(m=5,meth='cart')%>%
  complete()



```



# building model

```{r}
# 70% training set
train = sample(seq(num_cases),size = round(num_cases*.7))
train_set = imputed[train,]
test_set = imputed[-train,]


model1 = lm(SalePrice~., train_set)
summary(model1)

```

# model 2

```{r}
# using features with only numeric values
numeric_df <- train_set %>% dplyr::select(where(is.numeric))
model2 <- lm(SalePrice~., numeric_df)
summary(model2)
```

```{r}
# looking at residuals
ggplot(data = model2, aes(x = .fitted, y = .resid)) +
  geom_point() + geom_hline(yintercept = 0, linetype = "dashed") +
  geom_smooth(se = FALSE) + xlab("Fitted values") + ylab("Residuals")

ggplot(data = model_two, aes(x = .resid)) + geom_histogram() + xlab("Residuals")

ggplot(data = model_two) + stat_qq(aes(sample = .stdresid)) + geom_abline()
```


